services:
  # Backend API Service
  - type: web
    name: offer-hub-backend
    env: node
    region: oregon
    plan: free
    nodeVersion: 20
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: STELLAR_ADMIN_SECRET_KEY
        sync: false
      - key: USER_REGISTRY_CONTRACT_ID
        sync: false
      - key: STELLAR_RPC_URL
        value: https://rpc-futurenet.stellar.org:443
      - key: STELLAR_NETWORK_PASSPHRASE
        value: Test SDF Future Network ; October 2022

