/**
 * Error Codes
 * @see docs/api/errors.md
 */
export const ERROR_CODES = {
    // Authentication (401, 403)
    UNAUTHORIZED: 'UNAUTHORIZED',
    INVALID_API_KEY: 'INVALID_API_KEY',
    INSUFFICIENT_SCOPE: 'INSUFFICIENT_SCOPE',

    // Validation (400)
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INVALID_AMOUNT_FORMAT: 'INVALID_AMOUNT_FORMAT',
    INVALID_CURRENCY: 'INVALID_CURRENCY',
    MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

    // Users (404, 422)
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    AIRTM_USER_NOT_LINKED: 'AIRTM_USER_NOT_LINKED',
    AIRTM_USER_INVALID: 'AIRTM_USER_INVALID',
    AIRTM_USER_ALREADY_LINKED: 'AIRTM_USER_ALREADY_LINKED',

    // Balance / Funds (422, 409)
    INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
    FUNDS_ALREADY_RESERVED: 'FUNDS_ALREADY_RESERVED',
    RESERVE_NOT_FOUND: 'RESERVE_NOT_FOUND',
    RESERVE_MISMATCH_AMOUNT: 'RESERVE_MISMATCH_AMOUNT',

    // Orders / State Machine (404, 409)
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
    INVALID_STATE: 'INVALID_STATE',
    ESCROW_ALREADY_EXISTS: 'ESCROW_ALREADY_EXISTS',
    ESCROW_NOT_READY: 'ESCROW_NOT_READY',
    DISPUTE_ALREADY_OPEN: 'DISPUTE_ALREADY_OPEN',

    // Providers (502, 504)
    PROVIDER_ERROR: 'PROVIDER_ERROR',
    PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT',
    PROVIDER_RATE_LIMITED: 'PROVIDER_RATE_LIMITED',
    WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
    WEBHOOK_DUPLICATE_IGNORED: 'WEBHOOK_DUPLICATE_IGNORED',

    // Withdrawals (404, 409, 422)
    WITHDRAWAL_NOT_FOUND: 'WITHDRAWAL_NOT_FOUND',
    WITHDRAWAL_NOT_COMMITTABLE: 'WITHDRAWAL_NOT_COMMITTABLE',
    WITHDRAWAL_DESTINATION_INVALID: 'WITHDRAWAL_DESTINATION_INVALID',

    // Top-ups
    TOPUP_NOT_FOUND: 'TOPUP_NOT_FOUND',

    // Disputes
    DISPUTE_NOT_FOUND: 'DISPUTE_NOT_FOUND',

    // Idempotency (409)
    IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
    IDEMPOTENCY_KEY_IN_PROGRESS: 'IDEMPOTENCY_KEY_IN_PROGRESS',

    // Rate Limiting (429)
    RATE_LIMITED: 'RATE_LIMITED',

    // Internal (500)
    INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * HTTP status codes for each error code
 */
export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
    [ERROR_CODES.UNAUTHORIZED]: 401,
    [ERROR_CODES.INVALID_API_KEY]: 401,
    [ERROR_CODES.INSUFFICIENT_SCOPE]: 403,

    [ERROR_CODES.VALIDATION_ERROR]: 400,
    [ERROR_CODES.INVALID_AMOUNT_FORMAT]: 400,
    [ERROR_CODES.INVALID_CURRENCY]: 400,
    [ERROR_CODES.MISSING_REQUIRED_FIELD]: 400,

    [ERROR_CODES.USER_NOT_FOUND]: 404,
    [ERROR_CODES.USER_ALREADY_EXISTS]: 409,
    [ERROR_CODES.AIRTM_USER_NOT_LINKED]: 422,
    [ERROR_CODES.AIRTM_USER_INVALID]: 422,
    [ERROR_CODES.AIRTM_USER_ALREADY_LINKED]: 409,

    [ERROR_CODES.INSUFFICIENT_FUNDS]: 422,
    [ERROR_CODES.FUNDS_ALREADY_RESERVED]: 409,
    [ERROR_CODES.RESERVE_NOT_FOUND]: 404,
    [ERROR_CODES.RESERVE_MISMATCH_AMOUNT]: 422,

    [ERROR_CODES.ORDER_NOT_FOUND]: 404,
    [ERROR_CODES.INVALID_STATE]: 409,
    [ERROR_CODES.ESCROW_ALREADY_EXISTS]: 409,
    [ERROR_CODES.ESCROW_NOT_READY]: 409,
    [ERROR_CODES.DISPUTE_ALREADY_OPEN]: 409,

    [ERROR_CODES.PROVIDER_ERROR]: 502,
    [ERROR_CODES.PROVIDER_TIMEOUT]: 504,
    [ERROR_CODES.PROVIDER_RATE_LIMITED]: 502,
    [ERROR_CODES.WEBHOOK_SIGNATURE_INVALID]: 400,
    [ERROR_CODES.WEBHOOK_DUPLICATE_IGNORED]: 200,

    [ERROR_CODES.WITHDRAWAL_NOT_FOUND]: 404,
    [ERROR_CODES.WITHDRAWAL_NOT_COMMITTABLE]: 409,
    [ERROR_CODES.WITHDRAWAL_DESTINATION_INVALID]: 422,

    [ERROR_CODES.TOPUP_NOT_FOUND]: 404,

    [ERROR_CODES.DISPUTE_NOT_FOUND]: 404,

    [ERROR_CODES.IDEMPOTENCY_KEY_REUSED]: 409,
    [ERROR_CODES.IDEMPOTENCY_KEY_IN_PROGRESS]: 409,

    [ERROR_CODES.RATE_LIMITED]: 429,

    [ERROR_CODES.INTERNAL_ERROR]: 500,
};
